[package]
name = "trackie"
version = "0.1.0"
authors = ["beatbrot <loy.christoph@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.0-beta.2", default-features = false, features = ["std", "derive", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde"] }
dirs = "3.0.2"

[dev-dependencies]
spectral = "0.6.0"

[profile.release]
lto = true
codegen-units = 1