name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Publish artifact (Linux)
      uses: actions/upload-artifact@v2.2.4
      if: ${{ runner.os == 'Linux' }}
      with:
        name: "trackie-linux"
        path: "target/debug/trackie"
        if-no-files-found: error
    - name: Publish artifact (Win)
      uses: actions/upload-artifact@v2.2.4
      if: ${{ runner.os == 'Windows' }}
      with:
        name: "trackie-win"
        path: "target/debug/trackie.exe"
        if-no-files-found: warn
